# Generated by Django 5.2.6 on 2025-09-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.CharField(default='Nothing', max_length=100),
        ),
    ]
